spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    https://stackoverflow.com/questions/35576994/spring-jpa-application-properties-usessl
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_demo?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # 不加这句则默认为myisam引擎